# Generated by Django 3.1.4 on 2020-12-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Term', models.TextField(blank=True, max_length=100)),
                ('Sentence', models.TextField(blank=True)),
                ('Source', models.TextField(blank=True)),
            ],
        ),
    ]
