# Generated by Django 3.1.4 on 2020-12-24 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedterms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extractedterms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
