# Generated by Django 3.1.4 on 2020-12-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0002_auto_20201224_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledOnionLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
