# Generated by Django 3.1.4 on 2020-12-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0003_crawledonionlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('visited', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
